# Generated by Django 5.2.1 on 2026-03-28 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dollar (USD)'), ('EUR', 'Euro (EUR)')], default='BRL', max_length=3)),
                ('date_format', models.CharField(choices=[('dd/mm/yyyy', 'DD/MM/YYYY'), ('yyyy-mm-dd', 'YYYY-MM-DD')], default='dd/mm/yyyy', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
