# Generated by Django 5.2.1 on 2026-03-28 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'tipo', 'nome'], name='account_user_tipo_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'tipo', 'nome'], name='category_user_tipo_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'nome'], name='goal_user_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-data'], name='transaction_user_data_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'tipo', '-data'], name='transaction_user_tipo_data_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'account', '-data'], name='tx_user_acc_data_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', '-data'], name='tx_user_cat_data_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('import_fingerprint__isnull', False)), fields=('user', 'account', 'import_fingerprint'), name='transaction_unique_import_fingerprint_per_account'),
        ),
    ]
